const getCountryName = (countryCode: string | null): string | null => {
  const COUNTRY_NAMES: Record<string, string> = {
    US: "United States",
    IN: "India",
    GB: "United Kingdom",
    UK: "United Kingdom",
    DE: "Germany",
    FR: "France",
    CA: "Canada",
    AU: "Australia",
    BR: "Brazil",
    JP: "Japan",
    CN: "China",
    NL: "Netherlands",
    SG: "Singapore",
    ES: "Spain",
    IT: "Italy",
    SE: "Sweden",
    NO: "Norway",
    DK: "Denmark",
    FI: "Finland",
    RU: "Russia",
    MX: "Mexico",
    ZA: "South Africa",
    AE: "United Arab Emirates",
    SA: "Saudi Arabia",
    ID: "Indonesia",
    PK: "Pakistan",
    BD: "Bangladesh",
    AR: "Argentina",
    CL: "Chile",
    CO: "Colombia",
    PE: "Peru",
    VE: "Venezuela",
    KR: "South Korea",
    HK: "Hong Kong",
    TW: "Taiwan",
    TH: "Thailand",
    MY: "Malaysia",
    PH: "Philippines",
    VN: "Vietnam",
    TR: "Turkey",
    GR: "Greece",
    PT: "Portugal",
    IE: "Ireland",
    BE: "Belgium",
    AT: "Austria",
    CH: "Switzerland",
    PL: "Poland",
    CZ: "Czechia",
    HU: "Hungary",
    RO: "Romania",
    UA: "Ukraine",
    IL: "Israel",
    NZ: "New Zealand",
    NG: "Nigeria",
    EG: "Egypt",
    KE: "Kenya",
    MA: "Morocco",
    TN: "Tunisia",
    QA: "Qatar",
    KW: "Kuwait",
    BH: "Bahrain",
    OM: "Oman",
  };

  return countryCode ? COUNTRY_NAMES[countryCode] || countryCode : null;
};

export default getCountryName;
